from enum import StrEnum


class FactorCode(StrEnum):
    SYMBOL_RELEVANCE = "SYMBOL_RELEVANCE"
    EVENT_DIRECTION = "EVENT_DIRECTION"
    MATERIALITY = "MATERIALITY"
    NOVELTY = "NOVELTY"
    PERSISTENCE = "PERSISTENCE"
    THESIS_BREAK_RISK = "THESIS_BREAK_RISK"
    UNCERTAINTY = "UNCERTAINTY"
    INDUSTRY_SPILLOVER = "INDUSTRY_SPILLOVER"


class FactorValueType(StrEnum):
    CHOICE = "CHOICE"
    SCORE = "SCORE"
    NOUL = "NOUL"


class ProviderStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    DEGRADED = "DEGRADED"
    UNAVAILABLE = "UNAVAILABLE"
    ERROR = "ERROR"
